php-version = "8.1"

[source]
paths = ["composer", "scripts"]
includes = ["vendor"]
excludes = ["scripts/local"]

[linter.rules]
ambiguous-function-call = { enabled = true, level = "error" }
cyclomatic-complexity = { threshold = 6 }
kan-defect = { threshold = 1.9 }
halstead = { effort-threshold = 7000 }
literal-named-argument = { enabled = false }
too-many-enum-cases = { threshold = 30 }
# Enable disabled-by-default rules
no-redundant-use = { enabled = true }
no-variable-variable = { enabled = true }
no-redundant-readonly = { enabled = true }
sensitive-parameter = { enabled = true }

[analyzer]
allow-possibly-undefined-array-keys = false
find-unused-expressions = true
no-boolean-literal-comparison = true
