php_version = "8.1"

[source]
paths = ["composer"]
includes = ["vendor"]
excludes = []

[linter]
integrations = ["symfony", "laravel"]

[linter.rules]
ambiguous-function-call = { enabled = false }
cyclomatic-complexity = { threshold = 20 }
kan-defect = { threshold = 1.9 }
halstead = { effort-threshold = 7000 }
literal-named-argument = { enabled = false }
