[package]
name = "mago-wasm"
description = "Exposes PHP code analysis and tooling functionalities as WebAssembly modules, enabling browser-based tools and editor integrations."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dependencies]
mago-reporting = { workspace = true }
mago-database = { workspace = true }
mago-php-version = { workspace = true }
mago-linter = { workspace = true }
mago-codex = { workspace = true }
mago-formatter = { workspace = true }
mago-analyzer = { workspace = true }
mago-guard = { workspace = true }
mago-orchestrator = { workspace = true }
mago-prelude = { workspace = true, features = ["build"] }
wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
serde = { workspace = true }
